### PR TITLE
Static public holidays check

### PR DESCRIPTION
**Pull request by vrbros**
*Issue #, if available:*

*Description of changes: Added a sample script for holiday check from within the Lambda function.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by ranman** [comment]
Can you rebase this off of the current master please?

Also how is this different from the existing holiday check. Could the existing holiday check be modified to satisfy this need?

**Comment by vrbros** [comment]
Hi Randall,

Rebased.

It also allows you to store holiday names that can be spoken to the caller using Text to speech (Polly). The second different I see is that it stores the holiday list in a variable instead of Environment variables, making slightly easier for non tech users to use it. 

It mostly does what the existing function does. (I didn't realize before committing that a function existed.

Cheers!!

**Comment by efh365** [comment]
Could you instead update the existing solution to include those changes? I don't think we should have two solutions that are so similar.

**Comment by kqia040** [comment]
Closing the PR for now. Please reopen or create a new PR if there are updates.

**Pull request closed without merging**
